server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/epiphany;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;          # "php" = the service name in docker-compose.yml
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ ^/(backups|staging|debug)(/.*)?$ {
        rewrite ^ /trap.php last;
    }

    location ~ ^/uploads/private(/.*)?$ {
        rewrite ^ /trap.php last;
    }

    location ~ /\. {
        deny all;
    }
}
